sudo: false
language: java
jdk:
  - oraclejdk8
services:
  - mysql
build:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_script:
  - chmod +x src/test/run.sh
script:
  - mvn clean verify
  - /src/test/run.sh